-- ╔════════════════════════════════════════════════════════════════════╗
-- ║  Hola! Express — Schema completo                                   ║
-- ║  Ejecutar UNA sola vez en SQL Editor de Supabase                   ║
-- ╚════════════════════════════════════════════════════════════════════╝

-- ─── Limpieza (descomentar para reinstalar desde cero) ──────────────
-- drop table if exists public.cuentas_a_pagar cascade;
-- drop table if exists public.egresos cascade;
-- drop table if exists public.items_pedido cascade;
-- drop table if exists public.pedidos cascade;
-- drop table if exists public.movimientos_stock cascade;
-- drop table if exists public.lotes cascade;
-- drop table if exists public.items_venta cascade;
-- drop table if exists public.ventas cascade;
-- drop table if exists public.caja_turnos cascade;
-- drop table if exists public.productos cascade;
-- drop table if exists public.proveedores cascade;
-- drop table if exists public.categorias cascade;
-- drop table if exists public.usuarios cascade;
-- drop type if exists public.rol cascade;
-- drop type if exists public.estado_turno cascade;
-- drop type if exists public.medio_pago cascade;
-- drop type if exists public.estado_venta cascade;
-- drop type if exists public.estado_lote cascade;
-- drop type if exists public.tipo_movimiento cascade;
-- drop type if exists public.estado_pedido cascade;
-- drop type if exists public.estado_cuenta_pagar cascade;

-- ─── Enums ──────────────────────────────────────────────────────────

create type public.rol as enum ('admin', 'encargado', 'cajero');
create type public.estado_turno as enum ('abierto', 'cerrado');
create type public.medio_pago as enum ('efectivo', 'debito', 'credito', 'transferencia');
create type public.estado_venta as enum ('completada', 'anulada');
create type public.estado_lote as enum ('activo', 'agotado', 'vencido', 'dado_de_baja');
create type public.tipo_movimiento as enum ('entrada', 'salida', 'ajuste', 'merma', 'venta');
create type public.estado_pedido as enum ('borrador', 'enviado', 'recibido', 'cancelado');
create type public.estado_cuenta_pagar as enum ('pendiente', 'pagada', 'vencida');

-- ─── Tabla: usuarios ────────────────────────────────────────────────

create table public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  nombre text not null,
  rol public.rol not null default 'cajero',
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

-- ─── Tabla: categorias ──────────────────────────────────────────────

create table public.categorias (
  id integer generated by default as identity primary key,
  nombre text not null unique,
  descripcion text,
  created_at timestamptz not null default now()
);

-- ─── Tabla: proveedores ─────────────────────────────────────────────

create table public.proveedores (
  id integer generated by default as identity primary key,
  nombre text not null,
  telefono text,
  email text,
  dias_entrega integer check (dias_entrega is null or dias_entrega >= 0),
  condicion_pago text,
  created_at timestamptz not null default now()
);

-- ─── Tabla: productos ───────────────────────────────────────────────

create table public.productos (
  id integer generated by default as identity primary key,
  codigo_barras text unique,
  nombre text not null,
  categoria_id integer references public.categorias(id) on delete set null,
  proveedor_id integer references public.proveedores(id) on delete set null,
  precio_venta numeric(12, 2) not null check (precio_venta >= 0),
  precio_costo numeric(12, 2) not null default 0 check (precio_costo >= 0),
  stock_actual integer not null default 0,
  stock_minimo integer not null default 5 check (stock_minimo >= 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index productos_categoria_idx on public.productos(categoria_id);
create index productos_proveedor_idx on public.productos(proveedor_id);
create index productos_activo_idx on public.productos(activo) where activo = true;

-- ─── Tabla: caja_turnos ─────────────────────────────────────────────

create table public.caja_turnos (
  id integer generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id),
  fecha_apertura timestamptz not null default now(),
  fecha_cierre timestamptz,
  monto_apertura numeric(12, 2) not null default 0 check (monto_apertura >= 0),
  monto_cierre_real numeric(12, 2),
  monto_cierre_esperado numeric(12, 2),
  diferencia numeric(12, 2),
  estado public.estado_turno not null default 'abierto',
  novedades text,
  created_at timestamptz not null default now()
);

create index caja_turnos_usuario_estado_idx on public.caja_turnos(usuario_id, estado);
create index caja_turnos_fecha_apertura_idx on public.caja_turnos(fecha_apertura desc);

-- ─── Tabla: ventas ──────────────────────────────────────────────────

create table public.ventas (
  id integer generated by default as identity primary key,
  turno_id integer not null references public.caja_turnos(id),
  usuario_id uuid not null references public.usuarios(id),
  fecha timestamptz not null default now(),
  total numeric(12, 2) not null check (total >= 0),
  medio_pago public.medio_pago not null,
  estado public.estado_venta not null default 'completada',
  created_at timestamptz not null default now()
);

create index ventas_turno_idx on public.ventas(turno_id);
create index ventas_fecha_idx on public.ventas(fecha desc);
create index ventas_estado_idx on public.ventas(estado);

-- ─── Tabla: items_venta ─────────────────────────────────────────────

create table public.items_venta (
  id integer generated by default as identity primary key,
  venta_id integer not null references public.ventas(id) on delete cascade,
  producto_id integer not null references public.productos(id),
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

create index items_venta_venta_idx on public.items_venta(venta_id);
create index items_venta_producto_idx on public.items_venta(producto_id);

-- ─── Tabla: lotes ───────────────────────────────────────────────────

create table public.lotes (
  id integer generated by default as identity primary key,
  producto_id integer not null references public.productos(id),
  fecha_vencimiento date not null,
  cantidad_inicial integer not null check (cantidad_inicial > 0),
  cantidad_actual integer not null check (cantidad_actual >= 0),
  fecha_ingreso timestamptz not null default now(),
  estado public.estado_lote not null default 'activo',
  created_at timestamptz not null default now()
);

create index lotes_producto_idx on public.lotes(producto_id);
create index lotes_vencimiento_idx on public.lotes(fecha_vencimiento) where estado = 'activo';

-- ─── Tabla: movimientos_stock ───────────────────────────────────────

create table public.movimientos_stock (
  id integer generated by default as identity primary key,
  producto_id integer not null references public.productos(id),
  tipo public.tipo_movimiento not null,
  cantidad integer not null,
  stock_anterior integer not null,
  stock_nuevo integer not null,
  referencia_id integer,
  usuario_id uuid not null references public.usuarios(id),
  nota text,
  created_at timestamptz not null default now()
);

create index movimientos_producto_idx on public.movimientos_stock(producto_id, created_at desc);
create index movimientos_tipo_fecha_idx on public.movimientos_stock(tipo, created_at desc);

-- ─── Tabla: pedidos ─────────────────────────────────────────────────

create table public.pedidos (
  id integer generated by default as identity primary key,
  proveedor_id integer not null references public.proveedores(id),
  usuario_id uuid not null references public.usuarios(id),
  fecha_pedido timestamptz not null default now(),
  fecha_entrega_esperada date,
  estado public.estado_pedido not null default 'borrador',
  total numeric(12, 2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index pedidos_proveedor_idx on public.pedidos(proveedor_id);
create index pedidos_estado_idx on public.pedidos(estado);
create index pedidos_fecha_idx on public.pedidos(fecha_pedido desc);

-- ─── Tabla: items_pedido ────────────────────────────────────────────

create table public.items_pedido (
  id integer generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id) on delete cascade,
  producto_id integer not null references public.productos(id),
  cantidad_pedida integer not null check (cantidad_pedida > 0),
  cantidad_recibida integer check (cantidad_recibida is null or cantidad_recibida >= 0),
  precio_costo numeric(12, 2) not null check (precio_costo >= 0),
  subtotal numeric(12, 2) not null check (subtotal >= 0)
);

create index items_pedido_pedido_idx on public.items_pedido(pedido_id);

-- ─── Tabla: egresos ─────────────────────────────────────────────────

create table public.egresos (
  id integer generated by default as identity primary key,
  descripcion text not null,
  monto numeric(12, 2) not null check (monto >= 0),
  categoria text not null,
  fecha date not null default current_date,
  usuario_id uuid not null references public.usuarios(id),
  created_at timestamptz not null default now()
);

create index egresos_fecha_idx on public.egresos(fecha desc);
create index egresos_categoria_idx on public.egresos(categoria);

-- ─── Tabla: cuentas_a_pagar ─────────────────────────────────────────

create table public.cuentas_a_pagar (
  id integer generated by default as identity primary key,
  pedido_id integer not null references public.pedidos(id),
  proveedor_id integer not null references public.proveedores(id),
  monto numeric(12, 2) not null check (monto >= 0),
  fecha_vencimiento date not null,
  fecha_pago date,
  estado public.estado_cuenta_pagar not null default 'pendiente',
  created_at timestamptz not null default now()
);

create index cuentas_a_pagar_estado_idx on public.cuentas_a_pagar(estado);
create index cuentas_a_pagar_vencimiento_idx on public.cuentas_a_pagar(fecha_vencimiento) where estado = 'pendiente';

-- ─── Trigger: updated_at automático en productos y pedidos ──────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger productos_set_updated_at
  before update on public.productos
  for each row execute procedure public.set_updated_at();

create trigger pedidos_set_updated_at
  before update on public.pedidos
  for each row execute procedure public.set_updated_at();

-- ─── Trigger: al crear auth.users, crear fila en public.usuarios ───
-- El primer usuario que se cree queda como 'cajero'. El admin lo promueve
-- después editando la fila desde Supabase Studio (o desde la app).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.usuarios (id, email, nombre, rol, activo)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    'cajero',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─── RLS (Row Level Security) ───────────────────────────────────────
-- Política mínima: todos los usuarios autenticados pueden leer y escribir.
-- Para producción, refinar por rol usando la columna `usuarios.rol`.

alter table public.usuarios enable row level security;
alter table public.categorias enable row level security;
alter table public.proveedores enable row level security;
alter table public.productos enable row level security;
alter table public.caja_turnos enable row level security;
alter table public.ventas enable row level security;
alter table public.items_venta enable row level security;
alter table public.lotes enable row level security;
alter table public.movimientos_stock enable row level security;
alter table public.pedidos enable row level security;
alter table public.items_pedido enable row level security;
alter table public.egresos enable row level security;
alter table public.cuentas_a_pagar enable row level security;

-- Política genérica: authenticated puede todo. Reemplazar por políticas
-- por rol al endurecer producción.
do $$
declare
  tabla text;
begin
  for tabla in
    select unnest(array[
      'usuarios', 'categorias', 'proveedores', 'productos',
      'caja_turnos', 'ventas', 'items_venta', 'lotes',
      'movimientos_stock', 'pedidos', 'items_pedido',
      'egresos', 'cuentas_a_pagar'
    ])
  loop
    execute format(
      'create policy "authenticated todo" on public.%I for all to authenticated using (true) with check (true)',
      tabla
    );
  end loop;
end;
$$;

-- ─── Realtime ───────────────────────────────────────────────────────
-- Habilita Realtime para las tablas que el dashboard necesita actualizar
-- en vivo. Si no se habilita, el dashboard sigue funcionando con
-- refetchOnWindowFocus + staleTime corto.

alter publication supabase_realtime add table public.ventas;
alter publication supabase_realtime add table public.caja_turnos;

-- ╔════════════════════════════════════════════════════════════════════╗
-- ║  Schema completo. Siguiente paso: ejecutar seed.sql                ║
-- ╚════════════════════════════════════════════════════════════════════╝
