-- ╔════════════════════════════════════════════════════════════════════╗
-- ║  Migration 001: tabla pagos_venta                                   ║
-- ║                                                                     ║
-- ║  Permite registrar múltiples medios de pago por venta (split        ║
-- ║  payment). El campo `ventas.medio_pago` se mantiene como el medio   ║
-- ║  "principal" (mayor monto) por compatibilidad con queries legacy.   ║
-- ║                                                                     ║
-- ║  Ejecutar UNA sola vez en SQL Editor de Supabase.                   ║
-- ╚════════════════════════════════════════════════════════════════════╝

create table public.pagos_venta (
  id integer generated by default as identity primary key,
  venta_id integer not null references public.ventas(id) on delete cascade,
  medio_pago public.medio_pago not null,
  monto numeric(12, 2) not null check (monto > 0),
  created_at timestamptz not null default now()
);

create index pagos_venta_venta_idx on public.pagos_venta(venta_id);
create index pagos_venta_medio_idx on public.pagos_venta(medio_pago);

-- RLS: misma política simple que el resto (authenticated puede todo)
alter table public.pagos_venta enable row level security;

create policy "authenticated todo" on public.pagos_venta
  for all to authenticated using (true) with check (true);

-- Listo. Ahora todas las ventas registran sus pagos en pagos_venta,
-- y `ventas.medio_pago` queda como medio principal.
