-- ╔════════════════════════════════════════════════════════════════════╗
-- ║  Migration 004: cuentas y movimientos de cuenta                     ║
-- ║                                                                     ║
-- ║  Sistema contable simple: cada movimiento de dinero (ingreso,       ║
-- ║  egreso, transferencia) afecta una o dos cuentas. Las cuentas       ║
-- ║  representan dónde está físicamente la plata: caja efectivo,        ║
-- ║  cuentas bancarias, billeteras virtuales, etc.                      ║
-- ║                                                                     ║
-- ║  Ejecutar UNA sola vez en SQL Editor de Supabase.                   ║
-- ╚════════════════════════════════════════════════════════════════════╝

-- ─── Enums ──────────────────────────────────────────────────────────

do $$ begin
  create type public.tipo_cuenta as enum ('caja', 'banco', 'billetera_virtual');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.tipo_movimiento_cuenta as enum (
    'ingreso',
    'egreso',
    'transferencia_entrada',
    'transferencia_salida',
    'ajuste'
  );
exception when duplicate_object then null;
end $$;

-- ─── Tabla: cuentas ────────────────────────────────────────────────

create table if not exists public.cuentas (
  id integer generated by default as identity primary key,
  nombre text not null,
  tipo public.tipo_cuenta not null default 'caja',
  saldo_actual numeric(14, 2) not null default 0,
  moneda text not null default 'ARS',
  banco text,
  numero_cuenta text,
  alias_cbu text,
  notas text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cuentas_tipo_idx on public.cuentas(tipo);
create index if not exists cuentas_activo_idx on public.cuentas(activo) where activo = true;

-- ─── Tabla: movimientos_cuenta ─────────────────────────────────────

create table if not exists public.movimientos_cuenta (
  id integer generated by default as identity primary key,
  cuenta_id integer not null references public.cuentas(id) on delete cascade,
  tipo public.tipo_movimiento_cuenta not null,
  monto numeric(14, 2) not null check (monto > 0),
  saldo_anterior numeric(14, 2) not null,
  saldo_nuevo numeric(14, 2) not null,
  descripcion text not null,
  categoria text,
  -- Para transferencias: la otra cuenta involucrada
  contraparte_cuenta_id integer references public.cuentas(id) on delete set null,
  -- Para vincular el movimiento con su origen (venta, pago de cuenta, etc.)
  referencia_tipo text,
  referencia_id integer,
  -- UUID compartido para las dos partes de una transferencia
  transferencia_id text,
  usuario_id uuid not null references public.usuarios(id),
  fecha date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists mov_cuenta_cuenta_idx on public.movimientos_cuenta(cuenta_id, fecha desc);
create index if not exists mov_cuenta_tipo_idx on public.movimientos_cuenta(tipo);
create index if not exists mov_cuenta_categoria_idx on public.movimientos_cuenta(categoria);
create index if not exists mov_cuenta_referencia_idx on public.movimientos_cuenta(referencia_tipo, referencia_id);
create index if not exists mov_cuenta_transferencia_idx on public.movimientos_cuenta(transferencia_id);
create index if not exists mov_cuenta_fecha_idx on public.movimientos_cuenta(fecha desc);

-- ─── Agregar cuenta_id a egresos (opcional) ─────────────────────────
-- Permite vincular cada egreso a una cuenta específica. Es nullable
-- para no romper los egresos existentes.

alter table public.egresos
  add column if not exists cuenta_id integer references public.cuentas(id) on delete set null;

create index if not exists egresos_cuenta_idx on public.egresos(cuenta_id);

-- ─── Trigger updated_at en cuentas ──────────────────────────────────

drop trigger if exists cuentas_set_updated_at on public.cuentas;
create trigger cuentas_set_updated_at
  before update on public.cuentas
  for each row execute procedure public.set_updated_at();

-- ─── RLS ───────────────────────────────────────────────────────────

alter table public.cuentas enable row level security;
alter table public.movimientos_cuenta enable row level security;

do $$ begin
  create policy "authenticated todo" on public.cuentas
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "authenticated todo" on public.movimientos_cuenta
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

-- ─── Seed: 3 cuentas iniciales ──────────────────────────────────────
-- Solo se insertan si no existen ya.

insert into public.cuentas (nombre, tipo, saldo_actual, moneda)
select 'Caja Efectivo', 'caja', 0, 'ARS'
where not exists (select 1 from public.cuentas where nombre = 'Caja Efectivo');

insert into public.cuentas (nombre, tipo, saldo_actual, moneda)
select 'Banco Principal', 'banco', 0, 'ARS'
where not exists (select 1 from public.cuentas where nombre = 'Banco Principal');

insert into public.cuentas (nombre, tipo, saldo_actual, moneda)
select 'Mercado Pago', 'billetera_virtual', 0, 'ARS'
where not exists (select 1 from public.cuentas where nombre = 'Mercado Pago');

-- ─── Refresh schema cache de PostgREST ──────────────────────────────

notify pgrst, 'reload schema';
